import = [
  "~/.config/alacritty/themes/catppuccin-dark.toml",
  "~/.config/alacritty/themes/dark.toml",
  "~/.config/alacritty/theme.toml",
  "$XDG_CONFIG_HOME/.config/alacritty/themes/catppuccin-dark.toml",
  "$XDG_CONFIG_HOME/.config/alacritty/themes/dark.toml",
  "$XDG_CONFIG_HOME/.config/alacritty/theme.toml",
]

[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = true

[env]
TERM = "alacritty"

[window]
padding = { x = 16, y = 16 }
dynamic_padding = true
