import = [
  "~/.config/alacritty/themes/catppuccin-latte.toml"
]

[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = true

[env]
TERM = "alacritty"

[window]
padding = { x = 12, y = 12 }
dynamic_padding = true
dimensions = { columns = 96, lines = 28 }
opacity = 1
