palette = 'catppuccin_mocha'

add_newline = false
format = '[\[](subtext0)$username[@](subtext1)$hostname $directory[\]](subtext0)$character'

[character]
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold red)'

[username]
format = '[$user]($style)'
style_root = 'red'
style_user = 'rosewater'
show_always = true

[hostname]
format = """
[w](lavender)\
[i](blue)\
[n](sapphire)\
[t](sky)\
[e](teal)\
[r](green)\
"""
style = 'subtext0'
ssh_only = false

[directory]
format = '[$path]($style)[$read_only]($read_only_style)'
style = 'bold lavender'
read_only = '[RO]'
read_only_style = 'red'
truncation_length = 1

[git_branch]
format = '[$branch](fg:subtext0)'

[git_status]
format = '[$all_status$ahead_behind](bg:base fg:mauve)'
style = 'bg:none fg:base'
conflicted = '='
ahead =	'⇡${count}'
behind = '⇣${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
up_to_date = '^'
untracked = '?${count}'
stashed = '\\$'
modified = '!${count}'
staged = '+${count}'
renamed = '»${count}'
deleted = '-${count}'

[palettes.catppuccin_mocha]
rosewater = '#f5e0dc'
flamingo = '#f2cdcd'
pink = '#f5c2e7'
mauve = '#cba6f7'
red = '#f38ba8'
maroon = '#eba0ac'
peach = '#fab387'
yellow = '#f9e2af'
green = '#a6e3a1'
teal = '#94e2d5'
sky = '#89dceb'
sapphire = '#74c7ec'
blue = '#89b4fa'
lavender = '#b4befe'
text = '#cdd6f4'
subtext1 = '#bac2de'
subtext0 = '#a6adc8'
overlay2 = '#9399b2'
overlay1 = '#7f849c'
overlay0 = '#6c7086'
surface2 = '#585b70'
surface1 = '#45475a'
surface0 = '#313244'
base = '#1e1e2e'
mantle = '#181825'
crust = '#11111b'
