add_newline = true
format = '''[$directory$git_branch$git_status$cmd_duration](fg:15)

'''

[directory]
format = '$path '

[git_branch]
format = 'git:\($branch\) '

[git_status]
format = '$all_status$ahead_behind'
ahead = '↑$count '
behind = '↓$count '
diverged = '↕$count '
up_to_date = ''
stashed = '◆$count '
untracked = '+$count '
deleted = '-$count '
modified = '~$count '
renamed = '→$count '
staged = '±$count '

[cmd_duration]
format = '\($duration\) '
min_time = 1
