palette = 'catppuccin_mocha'

add_newline = false
format = '$directory$git_branch $character'
right_format = '$cmd_duration$git_status'

[character]
success_symbol = '[](green bold)'
vicmd_symbol = '[](rosewater bold)'
error_symbol = '[](pink)'

[directory]
format = '[$path](bg:base fg:lavender bold)'

[git_branch]
format = '[#](fg:surface2)[$branch](fg:subtext0)'

[cmd_duration]
format = '[$duration](fg:subtext1) '

[git_status]
format = '[$all_status$ahead_behind](bg:base fg:mauve)'
style = 'bg:none fg:base'
conflicted = '='
ahead =	'⇡${count}'
behind = '⇣${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
up_to_date = '^'
untracked = '?${count}'
stashed = '\\$'
modified = '!${count}'
staged = '+${count}'
renamed = '»${count}'
deleted = '-${count}'

[palettes.catppuccin_mocha]
rosewater = '#f5e0dc'
flamingo = '#f2cdcd'
pink = '#f5c2e7'
mauve = '#cba6f7'
red = '#f38ba8'
maroon = '#eba0ac'
peach = '#fab387'
yellow = '#f9e2af'
green = '#a6e3a1'
teal = '#94e2d5'
sky = '#89dceb'
sapphire = '#74c7ec'
blue = '#89b4fa'
lavender = '#b4befe'
text = '#cdd6f4'
subtext1 = '#bac2de'
subtext0 = '#a6adc8'
overlay2 = '#9399b2'
overlay1 = '#7f849c'
overlay0 = '#6c7086'
surface2 = '#585b70'
surface1 = '#45475a'
surface0 = '#313244'
base = '#1e1e2e'
mantle = '#181825'
crust = '#11111b'
