gui:
  windowSize: 'half'
  scrollOffMargin: 5
  showBottomLine: false
  border: 'single'
  theme:
    activeBorderColor:
      - cyan
      - bold
    inactiveBorderColor:
      - blue
    searchingActiveBorderColor:
      - cyan
      - bold
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - blue # set to `default` to have no background colour
    cherryPickedCommitBgColor:
      - cyan
    cherryPickedCommitFgColor:
      - blue
    unstagedChangesColor:
      - red
    defaultFgColor:
      - default
